### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Jeisonx3** [supthunder/premeStock#4]
I can't get the script to stay monitoring, i got like 30+ working proxies every time i start the script this happens, 
<img width="650" alt="screen shot 2017-03-21 at 1 14 05 am" src="https://cloud.githubusercontent.com/assets/22186712/24133535/0c202214-0dd4-11e7-8ac0-760129e21fe1.png">

**Comment by supthunder** [comment]
Download and run in same folder: https://github.com/supthunder/premeStock/blob/master/run.py


Also no proxies are loaded, you have to paste proxies list from proxies.txt into proxies variable

**Comment by supthunder** [comment]
https://github.com/supthunder/premeStock/wiki/How-to-run

**Comment by Bleez103** [comment]
Unrelated: 

Is it possible to add Slack Integration into your script @supthunder

**Comment by Jeisonx3** [comment]
Is it possible to make the masterstock.py save masterstock.txt in this format {'170459':'Studded Belt'} (just like proxyloader.py)  instead of, to make it easier to copy and paste.

"category_name": "Accessories", 
                "id": 170459, 
                "image_url": "//d17ol771963kd3.cloudfront.net/128530/ca/r2u51G9hEqY.jpg", 
                "image_url_hi": "//d17ol771963kd3.cloudfront.net/128530/rc/r2u51G9hEqY.jpg", 
                "name": "Studded Belt", 
                "new_item": true, 
                "position": 30, 
                "price": 14800, 
                "sale_price": 0
            }

**Comment by supthunder** [comment]
@Bleez103 added slack
![image](https://cloud.githubusercontent.com/assets/10327547/24175252/87337c48-0e6b-11e7-849a-c5047668a00e.png)

**Comment by Bleez103** [comment]
Much appreciated @supthunder

**Comment by Jeisonx3** [comment]
quick question how can i make it tweet or use slack just for testing @supthunder

**Comment by supthunder** [comment]
@Jeisonx3 tweet: go to apps.twitter.com create an API key, and paste that in tokens.py, with slack just edit the slackMsg() -> slack_token variable in monitor.py

Links: 

1. [Twitter API Key](https://themepacific.com/how-to-generate-api-key-consumer-token-access-key-for-twitter-oauth/994/)
2. [Slack API Key](https://my.slack.com/services/new/bot)

**Comment by supthunder** [comment]
[To test uncomment this line](https://github.com/supthunder/premeStock/blob/master/monitor.py#L89)

**Comment by Jeisonx3** [comment]
@supthunder Getting this while testing.
<img width="383" alt="screen shot 2017-03-22 at 7 40 06 pm" src="https://cloud.githubusercontent.com/assets/22186712/24225570/94be7bac-0f37-11e7-8684-77fc022f2fc5.png">
<img width="446" alt="screen shot 2017-03-22 at 7 41 00 pm" src="https://cloud.githubusercontent.com/assets/22186712/24225582/a4d6c044-0f37-11e7-93e2-885ddfa70eee.png">

**Comment by Bleez103** [comment]
Slacked addition worked perfectly for this weeks release @supthunder . If you have a paypal I'd be happy to donate.

Will it be possible to do a restock say for Adidas with similar Slack compatibility?

**Comment by supthunder** [comment]
@Bleez103 will add more next week, busy this week with school
