### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Jeisonx3** [supthunder/premeStock#5]
Getting this every time i run masterstock.py
<img width="1437" alt="screen shot 2017-03-30 at 11 25 14 am" src="https://cloud.githubusercontent.com/assets/22186712/24512873/ba09c950-153d-11e7-8fe1-64a331f7561c.png">

**Comment by supthunder** [comment]
Are you using a proxy? if so proxy is banned. If not, try installing this: pip install requests[security]

**Comment by Jeisonx3** [comment]
No proxy, no VPN. It used to work fine for me, i tried 3 different wifi (IP) that can access supreme website even my phone hotspot still same thing, i already have requests[security] installed.

**Comment by supthunder** [comment]
Try updating OpenSSL http://stackoverflow.com/questions/15185661/update-openssl-on-os-x-with-homebrew
